# Generated by Django 6.0 on 2025-12-10 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_defective', models.PositiveIntegerField(default=0)),
                ('qty_spare', models.PositiveIntegerField(default=0)),
                ('qty_spare_amc', models.PositiveIntegerField(default=0)),
                ('qty_defective_amc', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IPSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Draft', 'Draft')], default='Open', max_length=20)),
                ('reporter_name', models.CharField(max_length=100)),
                ('submission_date', models.DateField(help_text='Must be Monday')),
                ('week_from', models.DateField()),
                ('week_to', models.DateField()),
                ('remarks', models.TextField(blank=True, help_text='Action Plan / Non-AMC')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Draft', 'Draft')], default='Open', max_length=20)),
                ('reporter_name', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('maintenance_type', models.CharField(max_length=100)),
                ('work_description', models.TextField()),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelayRoomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Draft', 'Draft')], default='Open', max_length=20)),
                ('reporter_name', models.CharField(max_length=100)),
                ('log_date', models.DateField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('opening_code', models.CharField(max_length=50)),
                ('sn_opening', models.CharField(max_length=50)),
                ('sn_closing', models.CharField(max_length=50)),
                ('reason_remarks', models.TextField(help_text='Reason for opening')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Draft', 'Draft')], default='Open', max_length=20)),
                ('reporter_name', models.CharField(max_length=100)),
                ('report_date', models.DateField(help_text='Date of reporting')),
                ('route', models.CharField(max_length=50)),
                ('failure_datetime', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
                ('is_under_amc', models.BooleanField(default=False)),
                ('is_under_warranty', models.BooleanField(default=False)),
                ('affected_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failure_locations', to='office.station')),
                ('csi_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.csiunit')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.manufacturer')),
                ('posting_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failure_postings', to='office.station')),
                ('reasons', models.ManyToManyField(related_name='reports', to='office.failurereason')),
                ('reporter_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.designation')),
                ('sectional_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.sectionalofficer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
