# Generated by Django 6.0 on 2025-12-10 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='failurereport',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipsentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.ipscompany'),
        ),
        migrations.AddField(
            model_name='ipsentry',
            name='module_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.ipsmoduletype'),
        ),
        migrations.AddField(
            model_name='ipsreport',
            name='csi_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.csiunit'),
        ),
        migrations.AddField(
            model_name='ipsreport',
            name='reporter_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.designation'),
        ),
        migrations.AddField(
            model_name='ipsreport',
            name='sectional_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.sectionalofficer'),
        ),
        migrations.AddField(
            model_name='ipsreport',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipsentry',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='forms.ipsreport'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='csi_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.csiunit'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='reporter_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.designation'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='sectional_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.sectionalofficer'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='station_maintained',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.station'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relayroomlog',
            name='csi_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.csiunit'),
        ),
        migrations.AddField(
            model_name='relayroomlog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.station'),
        ),
        migrations.AddField(
            model_name='relayroomlog',
            name='reporter_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.designation'),
        ),
        migrations.AddField(
            model_name='relayroomlog',
            name='sectional_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.sectionalofficer'),
        ),
        migrations.AddField(
            model_name='relayroomlog',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ipsreport',
            unique_together={('csi_unit', 'week_from')},
        ),
        migrations.AlterUniqueTogether(
            name='ipsentry',
            unique_together={('report', 'module_type', 'company')},
        ),
    ]
