# Generated by Django 6.0 on 2025-12-13 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='reporter_designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='station_maintained',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='report_date',
            new_name='submission_date',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='reporter_name',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='work_description',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='asset_count',
            field=models.IntegerField(blank=True, help_text='Number of points maintained', null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='asset_id',
            field=models.CharField(blank=True, help_text='LC Gate Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='section',
            field=models.CharField(default=datetime.datetime(2025, 12, 13, 13, 55, 48, 75048, tzinfo=datetime.timezone.utc), help_text='e.g., ADI-SHB', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='staff_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='maintenance_type',
            field=models.CharField(choices=[('Point Maintenance', 'Point Maintenance'), ('Signal Maintenance', 'Signal Maintenance'), ('IPS/Power Supply', 'IPS/ Power Supply including battery maintenance'), ('LC Gate Maintenance', 'LC gate Maintenance')], max_length=100),
        ),
    ]
