# Generated by Django 6.0 on 2025-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_reporter_designation_maintenancereport_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='station',
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='asset_count',
            field=models.IntegerField(blank=True, help_text='No. of Points (if Point Maintenance)', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='asset_id',
            field=models.CharField(blank=True, help_text='LC Gate No (if LC Gate Maintenance)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='maintenance_type',
            field=models.CharField(choices=[('Point Maintenance', 'Point Maintenance'), ('Signal Maintenance', 'Signal Maintenance'), ('IPS/Power Supply', 'IPS/Power Supply'), ('LC Gate Maintenance', 'LC Gate Maintenance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='section',
            field=models.CharField(help_text='Section Code (e.g. ADI-SHB)', max_length=100),
        ),
    ]
