# Generated by Django 6.0 on 2025-12-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_maintenancereport_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='asset_count',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='asset_id',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='asset_numbers',
            field=models.CharField(blank=True, help_text='List of Asset IDs (e.g. Pt-101, LC-42)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='work_description',
            field=models.TextField(blank=True, help_text='Details of work carried out'),
        ),
    ]
