# Generated by Django 6.0 on 2025-12-15 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_maintenancereport_asset_count_and_more'),
        ('office', '0003_alter_station_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relayroomlog',
            old_name='reason_remarks',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='relayroomlog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relay_logs', to='office.station'),
        ),
        migrations.AlterField(
            model_name='relayroomlog',
            name='log_date',
            field=models.DateField(db_column='date'),
        ),
    ]
