# Generated by Django 6.0 on 2025-12-15 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_rename_reason_remarks_relayroomlog_remarks_and_more'),
        ('office', '0003_alter_station_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACFailureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Draft', 'Draft')], default='Open', max_length=20)),
                ('reporter_name', models.CharField(max_length=100)),
                ('location_code', models.CharField(max_length=50)),
                ('total_ac_units', models.IntegerField(default=0)),
                ('ac_type', models.CharField(choices=[('Split', 'Split'), ('Window', 'Window')], max_length=20)),
                ('total_fail_count', models.CharField(max_length=20)),
                ('failure_date_time', models.DateTimeField()),
                ('under_warranty', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('under_amc', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('csi_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.csiunit')),
                ('reporter_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.designation')),
                ('sectional_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.sectionalofficer')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
