# Generated by Django 6.0 on 2025-12-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_acfailurereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('sectional_officer', models.CharField(max_length=100)),
                ('csi', models.CharField(max_length=100)),
                ('posting_station', models.CharField(max_length=50)),
                ('to_station', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SI/CSI Movement Report',
                'ordering': ['-date', '-submitted_at'],
            },
        ),
    ]
