# Generated by Django 6.0 on 2025-12-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_movementreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='JPCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100)),
                ('jpc_date', models.DateField()),
                ('total_points', models.IntegerField()),
                ('inspected_today', models.IntegerField()),
                ('total_inspected_cum', models.IntegerField()),
                ('pending_points', models.IntegerField()),
                ('inspection_by', models.CharField(choices=[('SI', 'SI'), ('CSI', 'CSI')], max_length=10)),
                ('inspector_name', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'JPC Inspection Report',
                'ordering': ['-jpc_date', '-submitted_at'],
            },
        ),
    ]
