# Generated by Django 6.0 on 2025-12-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_jpcreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementreport',
            options={},
        ),
        migrations.RemoveField(
            model_name='movementreport',
            name='posting_station',
        ),
        migrations.RemoveField(
            model_name='movementreport',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='movementreport',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='movementreport',
            name='to_station',
        ),
        migrations.AddField(
            model_name='movementreport',
            name='move_from',
            field=models.CharField(default='SBI', help_text='Location moving from or Leave status', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementreport',
            name='move_to',
            field=models.CharField(default='SAU', help_text='Location moving to', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movementreport',
            name='work_done',
            field=models.TextField(default='Scheduled Inspection', help_text='Description of work done'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movementreport',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movementreport',
            name='sectional_officer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
