# Generated by Django 6.0 on 2025-12-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csiunit',
            name='sectional_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csi_units', to='office.sectionalofficer'),
        ),
        migrations.AlterField(
            model_name='station',
            name='csi_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='office.csiunit'),
        ),
    ]
