# Generated by Django 6.0 on 2025-12-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_csiunit_sectional_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
