# Generated by Django 6.0 on 2025-12-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_alter_station_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('csi_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='si_units', to='office.csiunit')),
            ],
            options={
                'verbose_name': 'SI Unit',
                'unique_together': {('name', 'csi_unit')},
            },
        ),
        migrations.AddField(
            model_name='station',
            name='si_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='office.siunit'),
        ),
    ]
